//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatDbEntities : DbContext
    {
        public ChatDbEntities()
            : base("name=ChatDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<chatclient> chatclients { get; set; }
        public virtual DbSet<chatsupporter> chatsupporters { get; set; }
        public virtual DbSet<chatter> chatters { get; set; }
        public virtual DbSet<message> messages { get; set; }
    }
}
