//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Data {
    using System;
    using System.Collections.Generic;

    public partial class chat {
        public int ChatId { get; set; }
        public int ChatClientId { get; set; }
        public int ChatSupporterId { get; set; }
        public string Status { get; set; }

        public virtual chatclient chatclient { get; set; }
        public virtual chatsupporter chatsupporter { get; set; }
    }
}
